"use client"

import { useState } from "react"
import Link from "next/link"
import {
  ArrowLeft, FileText, Sparkles, Loader2, Copy, Check,
  Fuel, ChevronDown
} from "lucide-react"

const contentTypes = [
  { id: "blog", label: "Blog Post", description: "Long-form content for your blog" },
  { id: "social", label: "Social Media", description: "Posts for Twitter, LinkedIn, Instagram" },
  { id: "ad", label: "Ad Copy", description: "Compelling ads that convert" },
  { id: "email", label: "Email", description: "Professional email content" },
  { id: "product", label: "Product Description", description: "Compelling product copy" },
]

const tones = ["Professional", "Casual", "Friendly", "Authoritative", "Humorous"]

export default function ContentWriterPage() {
  const [contentType, setContentType] = useState("blog")
  const [topic, setTopic] = useState("")
  const [tone, setTone] = useState("Professional")
  const [keywords, setKeywords] = useState("")
  const [generating, setGenerating] = useState(false)
  const [result, setResult] = useState("")
  const [copied, setCopied] = useState(false)

  const handleGenerate = async () => {
    if (!topic.trim()) return

    setGenerating(true)
    setResult("")

    // Simulate AI generation (replace with actual API call)
    await new Promise(r => setTimeout(r, 2000))

    // Mock result
    setResult(`# ${topic}\n\nHere's your AI-generated content for "${topic}" in a ${tone.toLowerCase()} tone.\n\nThis is placeholder content that would be generated by the AI based on your inputs. The actual implementation would call your AI API endpoint.\n\n## Key Points\n\n- Point one about ${topic}\n- Another important aspect\n- Final consideration\n\n${keywords ? `\nKeywords incorporated: ${keywords}` : ""}`)

    setGenerating(false)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(result)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="p-8 max-w-4xl">
      {/* Header */}
      <div className="flex items-center gap-4 mb-8">
        <Link
          href="/dashboard/tools"
          className="p-2 rounded-lg bg-white/5 hover:bg-white/10 text-white/60 hover:text-white transition-all"
        >
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <FileText className="w-6 h-6 text-purple-400" />
            AI Content Writer
          </h1>
          <p className="text-white/60 mt-1">
            Generate high-quality content with AI
          </p>
        </div>
        <div className="ml-auto flex items-center gap-2 text-sm text-orange-400 bg-orange-500/10 px-3 py-1.5 rounded-lg">
          <Fuel className="w-4 h-4" />
          10 fuel per generation
        </div>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Input Form */}
        <div className="space-y-6">
          {/* Content Type */}
          <div>
            <label className="block text-sm font-medium text-white mb-2">
              Content Type
            </label>
            <div className="grid grid-cols-2 gap-2">
              {contentTypes.map(type => (
                <button
                  key={type.id}
                  onClick={() => setContentType(type.id)}
                  className={`p-3 rounded-xl text-left transition-all ${
                    contentType === type.id
                      ? "bg-purple-500/20 border-2 border-purple-500/50 text-white"
                      : "bg-white/5 border-2 border-transparent text-white/70 hover:bg-white/10"
                  }`}
                >
                  <div className="font-medium text-sm">{type.label}</div>
                  <div className="text-xs text-white/40 mt-0.5">{type.description}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Topic */}
          <div>
            <label className="block text-sm font-medium text-white mb-2">
              Topic / Subject
            </label>
            <textarea
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="What should the content be about?"
              rows={3}
              className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white placeholder:text-white/30 focus:outline-none focus:border-purple-500/50"
            />
          </div>

          {/* Tone */}
          <div>
            <label className="block text-sm font-medium text-white mb-2">
              Tone
            </label>
            <div className="flex flex-wrap gap-2">
              {tones.map(t => (
                <button
                  key={t}
                  onClick={() => setTone(t)}
                  className={`px-4 py-2 rounded-lg text-sm transition-all ${
                    tone === t
                      ? "bg-purple-500 text-white"
                      : "bg-white/5 text-white/70 hover:bg-white/10"
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          {/* Keywords */}
          <div>
            <label className="block text-sm font-medium text-white mb-2">
              Keywords (optional)
            </label>
            <input
              type="text"
              value={keywords}
              onChange={(e) => setKeywords(e.target.value)}
              placeholder="keyword1, keyword2, keyword3"
              className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white placeholder:text-white/30 focus:outline-none focus:border-purple-500/50"
            />
          </div>

          {/* Generate Button */}
          <button
            onClick={handleGenerate}
            disabled={!topic.trim() || generating}
            className="w-full flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-purple-500 to-pink-500 text-white font-medium hover:opacity-90 transition-all disabled:opacity-50"
          >
            {generating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5" />
                Generate Content
              </>
            )}
          </button>
        </div>

        {/* Result */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="block text-sm font-medium text-white">
              Generated Content
            </label>
            {result && (
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-sm text-white/60 hover:text-white transition-colors"
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4 text-green-400" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy
                  </>
                )}
              </button>
            )}
          </div>
          <div className="h-[400px] p-4 rounded-xl bg-zinc-900/50 border border-white/10 overflow-auto">
            {generating ? (
              <div className="h-full flex items-center justify-center">
                <div className="text-center">
                  <Loader2 className="w-8 h-8 animate-spin text-purple-400 mx-auto mb-3" />
                  <p className="text-white/60">Creating your content...</p>
                </div>
              </div>
            ) : result ? (
              <pre className="text-white/80 whitespace-pre-wrap font-sans text-sm">
                {result}
              </pre>
            ) : (
              <div className="h-full flex items-center justify-center">
                <div className="text-center text-white/40">
                  <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>Your generated content will appear here</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
